# Generated by Django 4.2.5 on 2023-10-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'ordering': ('-date',)},
        ),
    ]
